[package]
name = "netsim-tests"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
netsim = "0.2"
tokio-core = "0.1"
tokio-current-thread = "0.1"
libp2p = { path = "../rust-libp2p" }
