[package]
name = "netsim-tests"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
netsim = "0.2"
tokio = "0.1"
tokio-core = "0.1"
libp2p = { git = "https://github.com/libp2p/rust-libp2p" }
